### ISSUE TITLE
Works not on Opensuse

### ISSUE THREAD

**Issue by starflighter** [gianlucaborello/libprocesshider#1]
Hey, I tried this on Opensuse 13.2 (Kernel 4.8.6-7). 
But the result is that the commands ps, top show nothing anymore. The lists are completely empty. 
And the ls-Command doesn't work anymore (ls: cannot access : No such file or directory) until the ld.so.preload is removed.

Can you help me ?

Thanks 
starflighter

**Comment by gianlucaborello** [comment]
mmm it seems to be working for me, do you have anything special in your setup or better can you confirm you are able to reproduce it on a clean host?

```
# cat /etc/os-release
NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"
```

```
# ps aux | grep evil
root      1393  2.4  0.8  40056  9012 pts/1    S+   05:52   0:01 /usr/bin/python ./evil_script.py 1.2.3.4 22
#
```

```
# LD_PRELOAD=~/libprocesshider/libprocesshider.so ps aux | grep evil
#
```

**Comment by starflighter** [comment]
To get sure, I installed a new one from a ISO.
The /cat/os-release is the same as by my machine.
Process to hide: `sleep 9999`
I editet the line in processhider.c to `static const char* process_to_filter = "sleep 9999";`
and I type `make` with no error.
But if I try this (without the grep), than ps and top are totally empty.

`LD_PRELOAD=~/libprocesshider/libprocesshider.so ps aux`

![temp](https://cloud.githubusercontent.com/assets/23389327/20213978/996b2e18-a80b-11e6-92ed-7fb8a24ca6eb.PNG)

What could be wrong?

**Comment by starflighter** [comment]
Sorry, I accidentally closed it ;-)

**Comment by starflighter** [comment]
Are you able to reproduce it?

**Comment by gianlucaborello** [comment]
I still can't replicate it. Are you by any chance on 32 bit?

**Comment by starflighter** [comment]
Jep, it's 32bit.

**Comment by gianlucaborello** [comment]
I don't have access to the same opensuse on 32 bit, but I tried it on another 32 bit CentOS 6 and it's working fine, so I'm afraid I won't be able to help you more than this. If you provide me access to that vm I can try to see what it is, otherwise you should just use gdb and step into the library code and figure out what's making it filter every process.

**Comment by starflighter** [comment]
Hi,
I got the chance to try it at work on a SLES-system. It works well.
So, I don't know what's wrong with this opensuse-system but like you said, there is no generall error.
Then this issue is not important and will be closed - and thanks for your help.
